version: "3"

services:
  app:
    build: .
    env_file: .env
    volumes:
      - .:/home/app/
      - /home/app/node_modules
    depends_on:
      - postgres
    ports:
      - "3005:3005"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: shorty
      POSTGRES_DB: shorty
      POSTGRES_PASSWORD: shorty